### ISSUE TITLE
Revert deployer to be compatible with Java 1.7

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-local#10]
As a developer, I'd like to revert the [Java version to 1.7](https://github.com/spring-cloud/spring-cloud-deployer-local/blob/master/pom.xml#L18), so the local-deployer implementation would be consistent with Spring Boot. 

**Acceptance:**
- default java build/runtime compatibility is switched to 1.7
- ci plans updated with the right java agent

**Comment by trisberg** [comment]
I think we only need to update to the new Java 1.7 SPI version and leave this project as Java 1.8
