### ISSUE TITLE
Fix Docker remote debugging test

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-deployer-local#101]
The docker based app deployer test in debug mode requires special handling with the following changes:

1) In this test case, our test assertion to check the deployment status requires different approach for maven vs docker as maven goes through the deployer status deploying -> deployed whereas the docker resource deployment checks for the container process running status hence, it goes directly to `deployed` status. 

For docker based app, explicitly verify the docker container's log output on debug suspend message to verify the correctness of this test case.

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-deployer-local/commit/6eee669f4088af4ff1ca9a9cd406230d8fcfd284.
