### ISSUE TITLE
"Forward port" changes from docker app support refactoring to 2.0.x branch

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-deployer-local#103]
Given there are many changes that went into master which didn't make it to 2.0.x branch , we need to apply only the required changes from https://github.com/spring-cloud/spring-cloud-deployer-local/pull/100 into 2.0.x branch

**Comment by markpollack** [comment]
I am thinking we need to get rid of the 2.0.x branch since it is such a maintenance burden and all that has changed in the parent pom dependency.

**Comment by sabbyanandan** [comment]
Closing this in favor of spring-cloud/spring-cloud-deployer-local#108.
