### ISSUE TITLE
Question: Is the running process meta-data ever saved?

### ISSUE THREAD

**Issue by menelaosbgr** [spring-cloud/spring-cloud-deployer-local#111]
I was looking at the following code:

https://github.com/spring-cloud/spring-cloud-deployer-local/blob/0031f47683d05ea83dafa2a2504dd2ae3e8d5769/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployer.java#L70

Will restarting an application that uses the localAppDeployer currently mean that the AppInstance information is unavailable?

**Comment by menelaosbgr** [comment]
Aha.. I think the readme basically answers my question:

> It’s important to note that this deployer spawns new JVMs that are not monitored or maintained by this deployer. No attempts at high availability, fault tolerance, or resiliency are provided by the deployer. Since the deployer SPI expects an underlying platform to provide that level of resiliency, any use of this deployer in a production environment should be accompanied with additional monitoring at the app level (the apps this deployer deploys). This deployer will not be updated to take on those requirements. Therefore the user is encouraged to explore the CloudFoundry and Kubernetes variants as ways to meet them.

**Comment by mminella** [comment]
I'm closing this as it's not an issue.  Going forward, StackOverflow is the right place to ask questions like this.
