### ISSUE TITLE
Manage active Task Map

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-local#112]
A cleanup routine would be in place to make sure the Task PIDs in the `running` Map doesn't grow indefinitely. 

Following two items are out of scope for this issue.

~We would have a separate thread to double check whether the PID is still alive; if not, we will remove it from the Map.~

~Also, when a cleanup/destroy routine is invoked from SCDF, we will make sure to cleanup the PID from running Map. This is already in place for Streams; we would implement it for Tasks now.~

**Comment by tzolov** [comment]
What qualifies a Task as `alive`? The [LaunchState](https://github.com/spring-cloud/spring-cloud-deployer/blob/master/spring-cloud-deployer-spi/src/main/java/org/springframework/cloud/deployer/spi/task/LaunchState.java) defines the following states:  `launching`, `running`, `cancelled`, `complete`, `failed`, `error`, `unknown`.  
For which of them should we prune the task instance from the running map?  
I guess that the `launching` and `running` should not be removed and the `cancelled` needs to be removed. 
What about  the `complete`, `failed`, `error`, `unknown` states?
