### ISSUE TITLE
Enhancement: Save state to disk or db in order to survive restart

### ISSUE THREAD

**Issue by menelaosbgr** [spring-cloud/spring-cloud-deployer-local#113]
Just an enhancement if possible - It would be nice to have the state saved to disk so that an application that uses this deployer will not lose track of the processes after a restart of the application.

I have implemented my own fork of this deployer where I convert data into a JSON string saved to DB, and deserialized it back. 
My only issue was with the process object but I worked around this - first version by checking for NULL process but if I rewrote it I would create a custom class extending abstract class process (if possible). 

In any case,  **it would be nice to have an official version for this functionality (if possible).**  
A copy of my hacked file (just an idea) though I am sure there are better ways of implementing this: https://gist.github.com/menelaosbgr/ee558d3cddfe6453843706be998c80fd#file-sglocalappdeployer-java

KR,
Menelaos

**Comment by markpollack** [comment]
I am hesitant to go in this direction, since it leads us down the road of creating a 'platform'.  I don't think what is there will work in the case that the application which launched the apps dies, since the child processes will also be killed.  The pid, stdout, etc, are all no longer relevant.

**Comment by menelaosbgr** [comment]
@markpollack Yes what you said is true. I noticed that in the case of a graceful termination (e.g. CTRL+C in the console), the child processes are also terminated. 

I think that this is due to the shutdown method that stops all processes  - and is executed with the @PreDestroy annotation: https://github.com/spring-cloud/spring-cloud-deployer-local/blob/master/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalAppDeployer.java#L251 .

Additionally, the case that the process is killed immediately (without allowing cleanup) - the child processes survive. I was only thinking in terms of recovering from a crash and/or sudden process termination not within the domain of normal application behavior.  

But it definitely adds quite a bit of complexity. It is understandable not wanting to create a platform when kivernities and so many others exist.

**Comment by markpollack** [comment]
I'll close the issue for now.  If there are some additional API changes so that a subclass would help you implement this functionality, I'll be happy to add it.  Thanks.
