### ISSUE TITLE
Instantiation differences to "workingDirectoriesRoot" in LocalTaskLauncher and LocalAppDeployer

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-local#168]
As a user, while using `workingDirectoriesRoot` property, I notice the instantiation differences between streams and tasks. 

Notes:
- Per-Stream/per-Task level deployer override doesn't seem to take into account (see: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3437)
- Instantiation code for `logPathRoot` is inconsistent between `LocalTaskLauncher` and `LocalAppDeployer`.
- The `logPathRoot` and `workingDirectoriesRoot` properties are instantiated and used interchangeably, but it is unclear which one takes precedence at what time in the lifecycle.
- Getter/setter for `workingDirectoriesRoot` is of different types.

**Comment by markpollack** [comment]
The implementation in inconsistent but the bigger issue is the functionality of overriding the workingDirectoriesRoot property at deployment time does not work as expected.

**Comment by markpollack** [comment]
In the PR I left the getter/setter mismatch for now, also there is a difference in the timestamp used in the temp dir, tasks uses nanoseconds and app uses milliseconds.

**Comment by ilayaperumalg** [comment]
This change is yet to be backported into 2.0.x

**Comment by ilayaperumalg** [comment]
This is now backported into 2.0.x as 70f387e
