### ISSUE TITLE
Implement scale() operation

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-local#172]
Depends https://github.com/spring-cloud/spring-cloud-deployer/issues/62

**Comment by jvalkeal** [comment]
We need to start tracking about what is a current preferred count of apps.

1. New scale operation needs to be blocking and thread safe if scaling is done in one method as parallel scale calls should not break anything, or...
2. We do scaling in a background thread and what scaling request does is just update preferred count.
