### ISSUE TITLE
Question: No tasks run after the first task when limited to one concurrent task

### ISSUE THREAD

**Issue by peavers** [spring-cloud/spring-cloud-deployer-local#183]
I'm in the discovery phase of figuring this all out so sorry if it's a silly question or if it should be on Stackoverflow

I have three different code bases, a task processor, a task launcher, and the task itself. I've limited the number of allowed running tasks to one.

I have many problems, but the first is that once the first task is recorded as complete in the database, no other tasks ever start. The deployer just keeps throwing even though no task is running.  

```java
2020-05-05 08:55:04.157 ERROR 33749 --- [HqZSZxdHMJIhw-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: error occurred during processing message in 'MethodInvokingMessageProcessor' [org.springframework.integration.handler.MethodInvokingMessageProcessor@6c43384e]; nested exception is java.lang.IllegalStateException: Cannot launch task terrible-thumbnail-creator. The maximum concurrent task executions is at its limit [1]
```

My task processor is just launching tasks via a stream:
```java
@Slf4j
@Service
@RequiredArgsConstructor
public class WorkerServiceImpl implements WorkerService {

    private final MessageService messageService;

    @Override
    public boolean createThumbnail(final String input, final String output) {

       // [...]

        final TaskLaunchRequest request = new TaskLaunchRequest(mavenUrl, inputList, null, null, "terrible-thumbnail-creator");

        return messageService.send(new GenericMessage<>(request));
    }
}
```
And I'm listening to that stream with just:
```java
@EnableTaskLauncher
@SpringBootApplication
public class Application {
  public static void main(final String[] args) {
    SpringApplication.run(Application.class, args);
  }
}
```
This is running the latest 2.3.0.RELEASE build. 

The actual task looks kinda list this (psudo)

```java
@EnableTask
@SpringBootApplication
public class Application {

  // [...]

  public static void main(final String[] args) {

    SpringApplication.run(Application.class, args);
  }

  @Bean
  public CommandLineRunner commandLineRunner() {

    return new TaskRunner(thumbnailService, messageService);
  }
```
If I add an `@AfterTask` to set a message, that is correctly saved to the database so I assume it is finished, do I need to do anything else? 

**Bonus question:** How do I handle all those failed tasks that get sent through while another task is running?

**Comment by sabbyanandan** [comment]
Hi, @peavers. Apologies for the delayed response. Questions like are better suited for StackOverflow indeed. If you can upload the sample Task application along with the configurations used, that'd help replicate it locally to then be able to answer your question(s).
