### ISSUE TITLE
How to run an application on a specified port 

### ISSUE THREAD

**Issue by tabish527112** [spring-cloud/spring-cloud-deployer-local#187]
How to run an application on a specified port, through properties?
The class LocalDeployerProperties does not define any such property.

**Comment by ilayaperumalg** [comment]
Hi, You should be able to use the Spring Boot property `server.port` for the application.

**Comment by tabish527112** [comment]
Actually I am tring to use SCDF, and need to define specific ports for all my apps. I tried using server.port, but then my stream wasnt deploying. Any ideas why this could be happening?

P.S. https://stackoverflow.com/questions/62062274/how-to-start-an-application-with-scdf-in-a-defined-port

**Comment by ilayaperumalg** [comment]
Please avoid creating the same question at multiple places. For any questions, you need to use SO and Github issues are meant for reporting any issues you might want to report.

Closing this as SO is the right place to handle this kind of questions.
