### ISSUE TITLE
Add "deploymentId" env var to apps deployed via LocalAppDeployer

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-local#36]
As a developer, I'd like to set `deploymentId` as an env-var to apps deployed via `LocalAppDeployer`.

**Comment by markpollack** [comment]
An environment variable such as `spring.cloud.deployer.deploymentId` should be set for each application that is launched.

**Comment by trisberg** [comment]
if it is an env var should it be "SPRING_CLOUD_DEPLOYER_DEPLOYMENT_ID"?

**Comment by markfisher** [comment]
I think we decided to hold off on these issues until we decide where the key determination belongs cc @markpollack

**Comment by sabbyanandan** [comment]
This story at each deployer implementation is irrelevant. @markpollack to update https://github.com/spring-cloud/spring-cloud-dataflow/issues/1248 with the latest findings/decisions.
