### ISSUE TITLE
LocalDeployerProperties declares JAVA_COMMAND incorrectly.

### ISSUE THREAD

**Issue by KingRokHead** [spring-cloud/spring-cloud-deployer-local#49]
Hi,

Attempting to execute mvnw test will always fail due to an incorrectly declared static constant "JAVA_COMMAND". It is set to "java". Tests that reference this class will fail when the private method "deduceJavaCommand" is called.
```
String javaExecutablePath = JAVA_COMMAND;
String javaHome = System.getProperty("java.home");
...
File javaExecutable = new File(javaHome, "bin/" + javaExecutablePath);
Assert.isTrue(javaExecutable.canExecute(), "Java executable discovered via 'java.home' system property '"
					+ javaHome + "' is not executable or does not exist.");
```

javaExecutable will resolve to %JAVA_HOME%/jre/java which can never be executable. Is this intended?

As it is defined currently the following Exception is raised and causes the tests to fail.
`Tests run: 11, Failures: 0, Errors: 11, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE!
testDirectJavaMemoryOptionWithG(org.springframework.cloud.deployer.spi.local.JavaExecutionCommandBuilderTests)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.IllegalArgumentException: Java executable discovered via 'java.home' system property 'F:\lib-tools\libs\java\jdk-1.8.0_60_x64\jre' is not executable or does not exist.`

**Comment by ericbottard** [comment]
This is likely because you're running maven with a JRE, not a JDK.

Although this should work on most platforms, it seems it does not work on yours.
- What does `./mvnw -v` emit?
- What is the layout of `F:\lib-tools\libs\java\jdk-1.8.0_60_x64\jre` on your machine?

**Comment by KingRokHead** [comment]
Hi.

> What is the layout of F:\lib-tools\libs\java\jdk-1.8.0_60_x64\jre on your machine?

The layout of my ...\jre is bin, lib plus all other child files under the jre directory - the original layout and content of the java distribution. There is no bin\java
This is not (in my opinion) an environment issue as I already performed all the necessary Googling to figure out why I was seeing the observed problems which led me to this class.
My JAVA_HOME is set correctly. "java.home" refers to JRE_HOME (Oracle documentation). My jdk bin is on my PATH out in front.

> What does ./mvnw -v emit?

Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)
Maven home: F:\lib-tools\tools\maven\apache-maven-3.5.0-bin\bin\..
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: F:\lib-tools\libs\java\jdk-1.8.0_60_x64\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "x86", family: "windows"

I stepped through the code and the toString of File returns "F:\lib-tools\libs\java\jdk-1.8.0_60_x64\jre\bin\java" which points to a non-existent _file_

> Although this should work on most platforms, it seems it does not work on yours.

I'm not sure how the below test harness _works_ on most platforms other then failing on the assertion.

I created a quick and simple test harness to demonstrate the behavior.

`
package com.tdt;
import java.io.File;
import org.junit.Assert;

public class TestJavaHome {
	public static String JAVA_COMMAND = "java";
	public static String JAVA_COMMAND_EXE = "java.exe";

	public static void main(String[] args){
		String javaExecutablePath = JAVA_COMMAND;
		String javaHome = System.getProperty("java.home");
		File javaExecutable = new File(javaHome, "bin/" + javaExecutablePath);
		Assert.assertTrue("Java executable discovered via 'java.home' system property '" + javaHome + "' is not executable or does not exist.", javaExecutable.canExecute());
	}
}`

The failed assertion is what is causing the tests to fail when running maven and ultimately the build to fail (although I know I can skip the tests).
The key point here is that "java" (without the file extension) points to nothing. If this is intended behavior  then please explain the apparent incorrect purpose as it currently exists in the code base.

Thanks.

**Comment by ericbottard** [comment]
In most java tool installations, JAVA_HOME is meant to point to a JDK installation (not a JRE).
I recommend changing this (at least for the session / script) that you use to launch SCDF

**Comment by KingRokHead** [comment]
Hi.

My JAVA_HOME is set to "F:\lib-tools\libs\java\jdk-1.8.0_60_x64" - the JDK. Which is the correct path for JAVA_HOME. It is not set to "F:\lib-tools\libs\java\jdk-1.8.0_60_x64\jre" which is what I think is your assumption.

There is no:
- F:\lib-tools\libs\java\jdk-1.8.0_60_x64\java, or 
- F:\lib-tools\libs\java\jdk-1.8.0_60_x64\jre\java or 
- F:\lib-tools\libs\java\jdk-1.8.0_60_x64\bin\java or 
- F:\lib-tools\libs\java\jdk-1.8.0_60_x64\jre\bin\java

ON a Windows environment, the code I provided above executes the same code in LocalDeployerProperties.java. 

_As it is coded_ the assertion will never hold true.

Am I missing something? Perhaps you could execute the main method I provided above, observe the results and tell me your execution passes true?

Or could you possibly explain why setting JAVA_COMMAND to "java" instead of "java.exe" is correct.

Thanks for your time.

**Comment by ericbottard** [comment]
My bad, I did not even realize there was the `.exe` extension problem.

`LocalDeployerProperties` being a `@ConfigurationProperties` class, you can override the value by setting eg the environment variable `SPRING_CLOUD_DEPLOYER_LOCAL_JAVA_CMD`

**Comment by ericbottard** [comment]
Please, could you confirm the above solution suits your needs? If so, feel free to close this issue.
Thanks

**Comment by sabbyanandan** [comment]
Hi, @KingRokHead: It'd be great if you can share your findings and close the issue.

**Comment by KingRokHead** [comment]
Hey,
Apologies for not responding sooner as I have been in the process of moving.

> LocalDeployerProperties being a @ConfigurationProperties class, you can override the value by setting eg the environment variable SPRING_CLOUD_DEPLOYER_LOCAL_JAVA_CMD

I will try the above work around within the week.

**Comment by manueljordan** [comment]
Hello 

I did the following combinations in the same console:

For JDK

* `SET SPRING_CLOUD_DEPLOYER_LOCAL_JAVA_CMD=C:\whiteroom\java\jdk1.8.0_131\bin`
* `SET SPRING_CLOUD_DEPLOYER_LOCAL_JAVA_CMD=C:\whiteroom\java\jdk1.8.0_131\bin;%PATH%`

For JRE

* `SET SPRING_CLOUD_DEPLOYER_LOCAL_JAVA_CMD=C:\whiteroom\java\jre1.8.0_131\bin`
* `SET SPRING_CLOUD_DEPLOYER_LOCAL_JAVA_CMD=C:\whiteroom\java\jre1.8.0_131\bin;%PATH%`

For any of these possible 4 options, I got the same issue yet.

Not sure if I am doing something wrong

**Comment by jvalkeal** [comment]
@ericbottard btw, I just PR'd #58 which relates to this.
