### ISSUE TITLE
Support deploying Boot 2.0 apps

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-deployer-local#62]
Looks like the way we provide the app args by adding them to the environment instead of as command line arguments has some issues with Boot 2.0 based apps. The integration tests set a random port  via `server.port` but the app always ends up using the default `8080`.

**Comment by markpollack** [comment]
Let's find out why env-var approach doesn't work before changing, as that should be a core boot feature.

**Comment by markpollack** [comment]
I think there may also be issues with max length of command line args.  Wonder is SAJ works...

**Comment by trisberg** [comment]
Well, we have this for the process builder:

```
builder.environment().putAll(args);
```

which means that the arg `server.port=1234` ends up in the env vars which Boot 1.5.x seems to resolve ok but 2.0 doesn't.

**Comment by jvalkeal** [comment]
Ok boot forces `XXX_DDD_UUU` format in `SystemEnvironmentPropertyMapper`. I never liked that local just passes normal properties into env variables but it's not fun to change it.

**Comment by trisberg** [comment]
Actually not that bad a change, I'll take a crack at it.
