### ISSUE TITLE
TaskLauncher adds server.port eventhough it is specified in args

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-deployer-local#77]
The task deployer checks to see if the server.port is in the properties https://github.com/spring-cloud/spring-cloud-deployer-local/blob/master/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalTaskLauncher.java#L89.  But does not check to see if it has been added to the arguments list.

**Comment by larrying** [comment]
#1665 issue is my question,If job failed, how to restart the failed job through UI.

**Comment by cppwfs** [comment]
Reopening -> https://github.com/spring-cloud/spring-cloud-dataflow/issues/1665  Let's pull this question back over there.
