### ISSUE TITLE
DeployerLocal adds all environment variables to command Line

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-deployer-local#88]
When attempting to run a task from the command line, all environment variables are added to the command line. 
This causes 2 problems: 
1) if the entry has no value boot throws an IllegalArgumentException as discussed here https://github.com/spring-cloud/spring-cloud-task/issues/369
2) If the user enumerates the datasource via environment properties it is not added to the command properly, because it uses underscores instead of dots.

While this solution may work for Docker, it does not work for running from the command line.

**Comment by mminella** [comment]
This approach also serves as a security issue.  Command line args are stored plain text in the database (and are also available via `ps -ef`).  Secure configurations like db credentials should not be passed as command line args and should _only_ be available via environment variables (or other secure configuration options).

**Comment by viniciusccarvalho** [comment]
@cppwfs I think the culprit is here correct? https://github.com/spring-cloud/spring-cloud-deployer-local/blob/master/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/AbstractLocalDeployerSupport.java#L200 

@markpollack We may need to have some sort of white list args we want to pass here. Besides the debug stuff that was added, anything else comes to your mind?

**Comment by mminella** [comment]
@viniciusccarvalho Whitelisting args isn’t a valid solution.  We need to not pass in all arguments as command line arguments.  They should be set as environment vars.

**Comment by cppwfs** [comment]
@viniciusccarvalho Sorry, I should have answered your question earlier.  Here is the line that is causing our fun: https://github.com/spring-cloud/spring-cloud-deployer-local/blob/e7cceab5ad39a8cd625bbd797e017baa20ff3e74/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/JavaCommandBuilder.java#L67
