### ISSUE TITLE
Set SPRING_APPLICATION_JSON as the default mode to pass properties for running apps

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-deployer-local#91]
Switch to `SPRING_APPLICATION_JSON` mode to pass application properties to apps
Make sure that if caller has already passed a `SPRING_APPLICATION_JSON` variable, we merge it with what the deployer passes to the application.

**Comment by sabbyanandan** [comment]
Closed in https://github.com/spring-cloud/spring-cloud-deployer-local/commit/4dda9de695842350eb33d7346582ecd1a4e1bafc.
