### ISSUE TITLE
Fix the failing Docker IT tests

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-local#99]
As a developer, I'd like to fix the failing Docker IT tests of the Local Deployer. 

**Acceptance:**
- `mvn clean install` is successful
- Once the PR is merged, we will have to update the CI plan to _not skip_ IT tests (remove `-DskipITs=true` [here](https://build.spring.io/build/admin/edit/editBuildTasks.action?buildKey=SCD-DLOCALMASTER-BSCDL)) on incremental commit-builds

**Comment by cppwfs** [comment]
When the user sets the `--spring.cloud.deployer.local.use-spring-application-json=false` the deployer is to use the environment variables instead of the SPRING_APPLICATION_JSON.  With the current snapshot the deployer is not setting the environment variables for the executed app.

**Comment by sabbyanandan** [comment]
The failing tests were addressed as part of the refactoring via https://github.com/spring-cloud/spring-cloud-deployer-local/commit/4643a75bd675b0e11aff43f021f948d769da3d74 and https://github.com/spring-cloud/spring-cloud-deployer-local/commit/6eee669f4088af4ff1ca9a9cd406230d8fcfd284
